name: "Cartoomics"
channels:
  - conda-forge
  - anaconda
  - default
dependencies:
  - python>=3.8.*,<3.12
  - tqdm>=4.64.0
  - gensim>=4.2.0
  - numpy>=1.22.4
  - scipy
  - pip
  - pip:
    - csrgraph>=0.1.28
    - nodevectors>=0.1.23
    - igraph>=0.9.10
    - py4cytoscape>=1.3.0
    - python-json-logger>=2.0.7
    - matplotlib>=3.7.2
    - seaborn>=0.12.2
<<<<<<< HEAD
    - beautifulsoup4>=4
    - bioservices>=1.7
    - shapely>=1.7
    - fiona>=1.8
    - geopandas>=0.9
    - unidecode>=1.3.8

    
=======

>>>>>>> d5d8b6201f05be3fce1a8283b169a3954306c5f1
