name: "Cartoomics"
channels:
  - conda-forge
  - anaconda
  - default
dependencies:
  - python=3.9.*
  - python-igraph
  - tqdm
  - gensim
  - numpy
  - pandas
  - scipy
  - argparse
  - regex
  - pip
  - pip:
    - py4cytoscape
    - csrgraph
    - nodevectors
